### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by rexiaji** [bluedazzle/wxpy#2]
py2版本
运行代码
```
from wxpy import *
bot = Bot()
embed() # 进入 Python 命令行

# 输入对象名称并回车
>>> bot
```
报错信息
UnicodeEncodeError: 'ascii' codec.......

因此错误实在是太普遍了，后续就不打了。。。

建议每个py文件的源代码前都加上

#coding=utf-8
"""doc说明"""
from __future__ import unicode_literals

**Comment by bluedazzle** [comment]
大兄弟你确定你下的是 py2 分支的代码吗？ master 分支的还是 py3 的。
https://github.com/bluedazzle/wxpy/tree/py2
请下载这个分支哈
